global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: demo-services
    honor_labels: true
    metrics_path: /metrics
    static_configs:
      - targets:
          - demo-service-a:8000
          - demo-service-b:8000
          - demo-service-c:8000
 EOF
