apiVersion: v1
kind: Service
metadata:
  name: demo-service
  namespace: predictive-autoscaling
spec:
  selector:
    app: demo-service
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP
